name: sqf_entity
homepage: https://github.com/qijie07/sqf_entity
description: SqfEntity ORM for Flutter/Dart lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework.
author:  Wyatt <storykym@gmail.com>
version: 2.3.1+7
publish_to: none

environment:
  sdk: '>=3.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: 3.0.0
  sqfentity_gen: 2.4.0
  synchronized: 3.1.0+1
  path: 1.9.0
  sqflite_common: 2.5.4
  sqflite_common_ffi: 2.3.3
  meta: 1.12.0

dependency_overrides:
  sqfentity_gen:
    git:
      url: https://github.com/Stewioie/sqfentity_gen.git
      ref: main
